Disable PM popup via setting
CnCNet/xna-cncnet-client pull request #237
Opened 2021-07-01 18:17 UTC by devo1929

2021-07-11 22:42 UTC, alexp8 commented
Tested with @devo1929 and works great well done :)

cc @Metadorius

2021-07-12 11:21 UTC, Metadorius requested changes
The code is OK, I left a bit of style notes in the comments. We use expression bodies for one-line statements in the client code.

2021-07-12 11:21 UTC, Metadorius commented on DXMainClient/Online/PrivateMessageHandler.cs
> +            }
```suggestion
            if (iu == null)
                return;
```

2021-07-12 11:21 UTC, Metadorius commented on DXMainClient/Online/PrivateMessageHandler.cs
> +            }
```suggestion
            if (_cncnetUserData.IsIgnored(iu.Ident))
                return;
```

2021-07-12 11:21 UTC, Metadorius commented on DXMainClient/Online/PrivateMessageHandler.cs
> +        }
```suggestion
        private void DoUnreadMessageCountUpdated()
            => UnreadMessageCountUpdated?.Invoke(this, new UnreadMessageCountEventArgs(UnreadMessageCount));
```

2021-07-12 11:21 UTC, Metadorius commented on DXMainClient/Online/PrivateMessageHandler.cs
> +        }
```suggestion
        public void ResetUnreadMessageCount()
            => SetUnreadMessageCount(0);
```

2021-07-12 11:21 UTC, Metadorius commented on DXMainClient/Online/PrivateMessageHandler.cs
> +        }
```suggestion
        public void IncrementUnreadMessageCount()
            => SetUnreadMessageCount(UnreadMessageCount + 1);
```

2021-07-12 11:21 UTC, Metadorius commented on DXMainClient/DXGUI/Generic/TopBar.cs
>          }
Any reason to leave this in such state?

2021-07-12 11:21 UTC, Metadorius commented on DXMainClient/DXGUI/Generic/TopBar.cs
> +        }
```suggestion
        private void PrivateMessageHandler_UnreadMessageCountUpdated(object sender, UnreadMessageCountEventArgs args)
            => UpdatePrivateMessagesBtnLabel(args.UnreadMessageCount);
```

2021-07-12 12:11 UTC, devo1929 commented
@Metadorius I addressed all of your suggestions.

2021-07-12 13:20 UTC, Metadorius approved these changes

2021-07-12 13:52 UTC, merged