Recent players list
CnCNet/xna-cncnet-client pull request #263
Opened 2021-10-24 16:59 UTC by devo1929

When a game starts, all players will be logged. In the PM window, there will be a tab for recent players, listing their names, the name of the game you played with them in, and when the game was played. The list will be ordered from newest to oldest. The list will only show the last 50 players. All right-click options for each player in this list should work like any other player list in this window.

The main purpose is to capture recent players so that you can add them to your friends list afterwards, if desired.

2021-11-27 00:31 UTC, devo1929 commented
![image](https://user-images.githubusercontent.com/2062360/143662505-8c781550-e998-4c9c-99d1-cface65fe1ab.png)

2021-11-27 22:27 UTC, Metadorius commented
IMO the list doesn't really work here, should do something like a table here.

2021-11-27 22:29 UTC, devo1929 commented
> IMO the list doesn't really work here, should do something like a table here.

Yea, I'm not a big fan of the way it looks either. I'll look into another approach.

2021-11-27 22:32 UTC, Metadorius commented
Look into tunnel selection window code, there's a table widget code there that can be used here.

2021-11-28 01:57 UTC, devo1929 commented
![image](https://user-images.githubusercontent.com/2062360/143726001-02e6038d-0329-4293-8991-bb95a2a60a05.png)

2021-11-28 12:42 UTC, Metadorius requested changes
A couple of nitpicks mainly on code style, otherwise code looks good.

2021-11-28 12:42 UTC, Metadorius commented on DXMainClient/DXGUI/Multiplayer/CnCNet/PrivateMessagingWindow.cs
> +        }
```suggestion
        private void RecentPlayersList_RightClick(object sender, IRCUser ircUser)
            => playerContextMenu.Show(ircUser, GetCursorPoint());
```

2021-11-28 12:42 UTC, Metadorius commented on DXMainClient/DXGUI/Multiplayer/CnCNet/PrivateMessagingWindow.cs
> +            }
```suggestion

            public void AddMessage(ChatMessage message)
                => XNAMessageBox.Show(windowManager, "Message", message.Message);
```

2021-11-28 12:42 UTC, Metadorius commented on DXMainClient/DXGUI/Multiplayer/CnCNet/RecentPlayerTable.cs
> +            }
```suggestion
            if (iu == null)
            {
                iu = new IRCUser(recentPlayer.PlayerName);
                isOnline = false;
            }

```

2021-11-28 12:42 UTC, Metadorius commented on DXMainClient/DXGUI/Multiplayer/CnCNet/PrivateMessagingWindow.cs
> +            }
```suggestion

            foreach (RecentPlayer recentPlayer in recentPlayers)
                mclbRecentPlayerList.AddRecentPlayer(recentPlayer);
```

2021-11-28 12:42 UTC, Metadorius commented on DXMainClient/DXGUI/Multiplayer/CnCNet/PrivateMessagingWindow.cs
> +            }
```suggestion
            foreach (var user in connectionManager.UserList)
                AddPlayerToList(user, true);
```

2021-11-28 12:48 UTC, devo1929 commented
@Metadorius all recent comments/clean up suggestions addressed

2021-11-28 12:49 UTC, Metadorius approved these changes

2021-11-28 12:49 UTC, merged