Update MultiplayerGameLobby controls visibility logic.
CnCNet/xna-cncnet-client pull request #318
Opened 2022-03-26 08:52 UTC by frg2089

This will provide more flexible control visibility support.
Applying different styles depending on the suffix will no longer be limited to "lbChatMessages" and "tbChatInput" controls.

Now we can write INI like this.
```ini
[MultiplayerGameLobby]
$CC-ChatMessages=ChatMessages:XNAPanel

[ChatMessages]
$X=1
$Y=1
$CC-lbChatMessages=lbChatMessages:ChatListBox

[ChatMessages_Host]
$BaseSection=ChatMessages
Size=100,200
BackgroundTexture=ChatMessagesBorder_Host.png

[ChatMessages_Player]
$BaseSection=ChatMessages
Size=100,100
BackgroundTexture=ChatMessagesBorder_Player.png
```
On `INItializableWindow` Initialized.
`ParseExtraControls()` method will create an `XNAPanel` named ChatMessages.

Then the `Refresh()` method will be called when creating a game or joining a game.
The ChatMessages control will be renamed to ChatMessages_Host or ChatMessages_Player via the `IsHost` field. and reload its properties.

2022-04-21 23:59 UTC, devo1929 approved these changes

2022-11-29 21:28 UTC, Metadorius requested changes
Couple of nitpicks. I am not quite sure this is the direction we want to take (with hardcoded suffixes and handling only the very special case of map list visibility), I would prefer a more generalized solution. But the execution of that idea is more or less fine.

@Rampastring what's your opinion? Basically the code is very specific to this case and introduces INI behavior based on section names, which is only tied to map box being shown or not.

2022-11-29 21:28 UTC, Metadorius commented on DXMainClient/DXGUI/Multiplayer/GameLobby/MultiplayerGameLobby.cs
> +                btnPickRandomMap.Enable();
Pretty sure you forgot `btnMapSortAlphabetically`. Also wouldn't tunnel selection button need to be handled too at CnCNet game lobby? Maybe would be good to have this function as protected virtual?

2022-11-29 21:28 UTC, Metadorius commented on DXMainClient/DXGUI/Multiplayer/GameLobby/MultiplayerGameLobby.cs
> +                sourceSuffix = "_Host";
```suggestion
                sourceSuffix = "_Host";
                targetSuffix = "_Player";
```

2022-11-29 21:28 UTC, Metadorius commented on DXMainClient/DXGUI/Multiplayer/GameLobby/MultiplayerGameLobby.cs
> +                targetSuffix = "_Host";
You should make those consts at class level.

2022-11-29 21:28 UTC, Metadorius commented on DXMainClient/DXGUI/Multiplayer/GameLobby/MultiplayerGameLobby.cs
> +            List<XNAControl> needUpdateControls = new List<XNAControl>(); // Controls that will be updated.
```suggestion
            List<XNAControl> controlsToUpdate = new();
```
Change the occurences accordingly.

2022-11-29 21:28 UTC, Metadorius commented on DXMainClient/DXGUI/Multiplayer/GameLobby/MultiplayerGameLobby.cs
> +        private void ChangeMapListAndOtherControlsVisibility(bool isHost)
Not fond of the name, needs something more concise.

2022-11-29 21:28 UTC, Metadorius commented on DXMainClient/DXGUI/Multiplayer/GameLobby/MultiplayerGameLobby.cs
> +                    s => ChangeMapListAndOtherControlsVisibility(true)),
No, you're mixing two things. The prefixes you have and the bool you use as a parameter suggest differentiation between host and player, yet you're mixing this with map list hidden or shown.

2026-06-06 08:08 UTC, closed without merging