Fixes .editorconfig and adds validation to workflows
CnCNet/xna-cncnet-client pull request #372
Opened 2022-09-14 19:22 UTC by Belonit

We use this workflow at Phobos and it works well

2022-09-15 20:23 UTC, Rans4ckeR commented
FYI we are planning to merge below PR before all others, which will generate quite some conflicts I'm afraid.
- https://github.com/CnCNet/xna-cncnet-client/pull/341

2022-09-19 17:12 UTC, Metadorius commented
I think it would be beneficial if you reset your branch to pre-fix and then reapply all warning fixes.

2022-09-19 17:14 UTC, Belonit commented
@Metadorius Yes, I'll do it a little later

2022-10-22 07:14 UTC, Belonit commented
I updated this PR and consider it is done

2022-11-24 19:41 UTC, Metadorius requested changes
The council ™️ concluded that the style checks should absolutely NOT fail a workflow. Instead look into making a problem matcher and registering it so that it displays issues as inline annotations (same applies for Phobos one as it's quite annoying to get failed runs just because of a stray trailing space): https://github.com/actions/toolkit/blob/main/docs/problem-matchers.md

2022-11-25 00:09 UTC, Belonit commented
> The council ™️ concluded that the style checks should absolutely NOT fail a workflow. Instead look into making a problem matcher and registering it so that it displays issues as inline annotations (same applies for Phobos one as it's quite annoying to get failed runs just because of a stray trailing space): https://github.com/actions/toolkit/blob/main/docs/problem-matchers.md

Currently, GitHub Actions limit the annotation count in a workflow run.

- 10 warning annotations, 10 error annotations, and 10 notice annotations per step
- 50 annotations per job (sum of annotations from all the steps)
- 50 annotations per run (separate from the job annotations, these annotations aren’t created by users)

If your workflow may exceed these annotation counts, consider filtering of the log messages which the Problem Matcher is exposed to (e.g. by PR touched files, lines, or other).

2022-11-25 00:14 UTC, Metadorius commented
I think those counts are reasonable and we can work with that. Not sure why you closed the PR though?

2022-11-25 00:45 UTC, Belonit commented
> I think those counts are reasonable and we can work with that. Not sure why you closed the PR though?

I'm not sure why it closed either. Possibly missclick

2025-08-01 12:04 UTC, Metadorius commented
Closing because of a huge load of conflicts and no progress on problem matcher, feel free to reopen/submit a new one, whichever is easier, if you get addressing the conflicts AND problem matcher which doesn't fail the workflow.

2025-08-01 12:04 UTC, closed without merging