Add notice for non-release builds
CnCNet/xna-cncnet-client pull request #578
Opened 2024-11-05 12:59 UTC by SadPencil

This PR adds a "(Development Build)" suffix in title bar, as well as a log message, for non-release builds.

A build is considered as a release build if the following conditions are met:
- The branch name is "master"
- The commit has a tag with a correct version number recognized by GitVersion

Also, this PR adds "rc" as the SemVer tag for non-release builds in master branch.

![Snipaste_2024-11-05_20-49-52](https://github.com/user-attachments/assets/e4d510fe-b11d-4097-a525-9297e1980b1e)

2024-11-26 22:04 UTC, MahBoiDeveloper commented
Artifact for TSC works as intended.

![image](https://github.com/user-attachments/assets/2f6afd1e-2a16-4952-9a99-ff584a020e08)

2024-11-26 22:13 UTC, MahBoiDeveloper commented
Self-builded binaries also works.

![image](https://github.com/user-attachments/assets/ecc0727f-588f-452d-98ac-e24cf9ebb9c7)

2024-11-26 22:21 UTC, MahBoiDeveloper requested changes

2024-11-26 22:21 UTC, MahBoiDeveloper commented on DXMainClient/DXGUI/GameClass.cs
> +            Window.Title += " (Development Build)";
Please, add L10N e.g., ` Window.Title += " " + "(Development Build)".L10N("Client:Main:DeveopmentBuildTitle");`

2024-11-26 23:37 UTC, Metadorius commented on DXMainClient/DXGUI/Multiplayer/CnCNet/CnCNetLobby.cs
> +                string developBuildWarningMessage = "This is a development build. Stability and reliability may not be fully guaranteed.".L10N("Client:Main:DevelopmentBuildWarning");
```suggestion
                string developBuildWarningMessage = "This is a development build of the client. Stability and reliability may not be fully guaranteed.".L10N("Client:Main:DevelopmentBuildWarning");
```

2024-11-27 07:53 UTC, SadPencil commented
@MahBoiDeveloper @Metadorius review comments addressed. Request re-review

2024-11-27 09:02 UTC, MahBoiDeveloper commented
All text are translatable.

Char warning message:
![image](https://github.com/user-attachments/assets/b4854efd-6965-4c45-bb39-47830ed02e09)

Title:
![image](https://github.com/user-attachments/assets/90eb6ad6-458a-4e35-9500-637e0e97de04)

INI key works as intended:
![image](https://github.com/user-attachments/assets/31853a29-57e8-4c87-a3c1-d349d04a888a)

2024-11-30 11:11 UTC, MahBoiDeveloper commented
Please, add this key with default value and description into https://github.com/CnCNet/xna-cncnet-client/blob/develop/DXMainClient/Resources/ClientDefinitions.ini

2024-12-01 18:30 UTC, MahBoiDeveloper commented
> Please, add this key with default value and description into https://github.com/CnCNet/xna-cncnet-client/blob/develop/DXMainClient/Resources/ClientDefinitions.ini

@SadPencil merge https://github.com/SadPencil/xna-cncnet-client/pull/6 into this branch please.

2024-12-03 18:22 UTC, Metadorius requested changes
It's also needed to write different file metadata for non-release builds. From what I understand currently the metadata is not altered.

2024-12-03 18:22 UTC, Metadorius commented on DXMainClient/DXGUI/GameClass.cs
> +#endif
Is it needed to translate parentheses? Maybe
```suggestion
                string developBuildTitle = "Development Build".L10N("Client:Main:DevelopmentBuildTitle");

#if DEVELOPMENT_BUILD
                if (ClientConfiguration.Instance.ShowDevelopmentBuildWarnings)
                    Window.Title += $" ({developBuildTitle})";
#endif
```

would work better?

2024-12-03 21:16 UTC, SadPencil commented
> It's also needed to write different file metadata for non-release builds. From what I understand currently the metadata is not altered.

Don't know way to achieve this

2024-12-04 00:09 UTC, MahBoiDeveloper commented
> > It's also needed to write different file metadata for non-release builds. From what I understand currently the metadata is not altered.
> 
> Don't know way to achieve this

Isn't already done?
![image](https://github.com/user-attachments/assets/0f0597e7-92f2-4110-8937-46ba7d1ae106)

2024-12-04 00:27 UTC, Metadorius commented
Eh that works too I guess. I would have preferred complete wipe of course. Maybe @frg2089 or @devo1929 could help

2024-12-06 02:53 UTC, merged