When there is only 1 player, the selection of random map will randomize to all maps
CnCNet/xna-cncnet-client pull request #583
Opened 2024-11-25 11:32 UTC by Flactine

When the number of players is 1, the random map will be assigned to any map, regardless of the max players of the map.
Used to randomly check maps.

2024-11-25 11:37 UTC, SadPencil commented on DXMainClient/DXGUI/Multiplayer/GameLobby/GameLobbyBase.cs
> +			}
Add a line break after }

2024-11-27 08:00 UTC, SadPencil requested changes
Note: please address the review comments before your PR gets merged

2024-12-06 02:19 UTC, SadPencil commented
@Flactine This is a reminder that please address the review comment since we want to merge this PR.

2024-12-06 02:24 UTC, Flactine reviewed
Good

2024-12-06 02:28 UTC, SadPencil commented
> Good

You need to **address** the review comment, which means you need to pushing more commits so that your codes does not violate the requirements. Not hitting the "Resolve conversation" button -- it just sent the information that **you** have addressed the comment, rather than automatically let GitHub solve it.

2024-12-06 02:41 UTC, SadPencil commented
@Flactine After you have addressed all concerns, please hit "Resolve conversation" button and then re-request reviews. See the screenshot below.

![](https://github.com/user-attachments/assets/ade4ae83-2706-4183-a2a5-d008442e7bad)

2024-12-06 02:45 UTC, SadPencil approved these changes

2024-12-06 02:49 UTC, merged